# Generated by Django 6.0.6 on 2026-09-10 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_add_tipo_motivazione'),
        ('stores', '0004_add_area_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EHSCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('durata_ore', models.DecimalField(decimal_places=1, max_digits=4)),
                ('descrizione', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('scadenza_giorni', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Corso EHS',
                'verbose_name_plural': 'Corsi EHS',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EHSPartecipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscritto_il', models.DateTimeField(auto_now_add=True)),
                ('presente', models.BooleanField(default=False)),
                ('assente_motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('attestato_file', models.FileField(blank=True, null=True, upload_to='ehs/attestati/')),
                ('attestato_caricato_il', models.DateTimeField(blank=True, null=True)),
                ('completato', models.BooleanField(default=False)),
                ('completato_il', models.DateTimeField(blank=True, null=True)),
                ('scadenza_formazione', models.DateField(blank=True, null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ehs_partecipazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partecipante EHS',
                'verbose_name_plural': 'Partecipanti EHS',
                'ordering': ['sessione', 'utente__cognome'],
            },
        ),
        migrations.CreateModel(
            name='EHSNotificaScadenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('letta', models.BooleanField(default=False)),
                ('letta_il', models.DateTimeField(blank=True, null=True)),
                ('negozio_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehs_notifiche_scadenza', to='stores.store')),
                ('partecipante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifica_scadenza', to='ehs.ehspartecipante')),
            ],
            options={
                'verbose_name': 'Notifica Scadenza EHS',
                'verbose_name_plural': 'Notifiche Scadenza EHS',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.CreateModel(
            name='EHSSessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('RICHIESTA_INVIATA', 'Richiesta inviata dallo store'), ('DATA_PROPOSTA', 'Data proposta dal fornitore'), ('DATA_CONTROPROPOSTA', 'Nuova data proposta dallo store'), ('CONFERMATA', 'Data confermata, docente assegnato'), ('REGISTRO_INVIATO', 'Registro inviato al negozio'), ('SVOLTA', 'Sessione svolta, registro compilato ricevuto'), ('COMPLETATA', 'Completata'), ('ANNULLATA', 'Annullata')], default='RICHIESTA_INVIATA', max_length=30)),
                ('data_proposta', models.DateTimeField(blank=True, null=True)),
                ('data_confermata', models.DateTimeField(blank=True, null=True)),
                ('durata_ore', models.DecimalField(decimal_places=1, max_digits=4)),
                ('docente_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('docente_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('contatto_negozio_nome', models.CharField(max_length=200)),
                ('contatto_negozio_telefono', models.CharField(max_length=30)),
                ('registro_file', models.FileField(blank=True, null=True, upload_to='ehs/registri/')),
                ('registro_compilato_file', models.FileField(blank=True, null=True, upload_to='ehs/registri_compilati/')),
                ('data_chiusura', models.DateTimeField(blank=True, null=True)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('calendario_evento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehs_sessione', to='events.evento')),
                ('chiusa_da', models.ForeignKey(blank=True, limit_choices_to={'livello_accesso': 'fornitore'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehs_sessioni_chiuse', to=settings.AUTH_USER_MODEL)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni', to='ehs.ehscorso')),
                ('creata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ehs_sessioni_create', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(blank=True, limit_choices_to={'livello_accesso': 'fornitore'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehs_sessioni_gestite', to=settings.AUTH_USER_MODEL)),
                ('negozio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ehs_sessioni', to='stores.store')),
            ],
            options={
                'verbose_name': 'Sessione EHS',
                'verbose_name_plural': 'Sessioni EHS',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.AddField(
            model_name='ehspartecipante',
            name='sessione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipanti', to='ehs.ehssessione'),
        ),
        migrations.CreateModel(
            name='EHSSessioneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_precedente', models.CharField(blank=True, max_length=30)),
                ('stato_nuovo', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True)),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='ehs.ehssessione')),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehs_log_azioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Sessione EHS',
                'verbose_name_plural': 'Log Sessioni EHS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ehspartecipante',
            unique_together={('sessione', 'utente')},
        ),
    ]
