# Generated by Django 6.0.6 on 2026-09-11 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehs', '0002_seed_corso_scale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ehssessione',
            name='data_suggerita_store',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ehssessione',
            name='partecipanti_previsti',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ehssessione',
            name='stato',
            field=models.CharField(choices=[('RICHIESTA_INVIATA', 'Richiesta inviata dallo store'), ('DATA_PROPOSTA', 'Data proposta dal fornitore'), ('DATA_CONTROPROPOSTA', 'Nuova data proposta dallo store'), ('CONFERMATA', 'Confermata'), ('COMPLETATA', 'Completata'), ('ANNULLATA', 'Annullata')], default='RICHIESTA_INVIATA', max_length=30),
        ),
        migrations.CreateModel(
            name='EHSNotificaSessioneConfermata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('letta', models.BooleanField(default=False)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehs_notifiche_conferma', to=settings.AUTH_USER_MODEL)),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_conferma', to='ehs.ehssessione')),
            ],
            options={
                'verbose_name': 'Notifica Conferma Sessione EHS',
                'verbose_name_plural': 'Notifiche Conferma Sessione EHS',
                'ordering': ['-creata_il'],
            },
        ),
    ]
