# Generated by Django 6.0.6 on 2026-09-11 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehs', '0003_ehssessione_data_suggerita_store_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EHSNotificaNuovaRichiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('letta', models.BooleanField(default=False)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehs_notifiche_richiesta', to=settings.AUTH_USER_MODEL)),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_richiesta', to='ehs.ehssessione')),
            ],
            options={
                'verbose_name': 'Notifica Nuova Richiesta EHS',
                'verbose_name_plural': 'Notifiche Nuova Richiesta EHS',
                'ordering': ['-creata_il'],
            },
        ),
    ]
