# Generated by Django 6.0.6 on 2026-09-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehs', '0004_ehsnotificanuovarichiesta'),
        ('stores', '0004_add_area_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHSNotificaDataProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('letta', models.BooleanField(default=False)),
                ('negozio_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehs_notifiche_data_proposta', to='stores.store')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_data_proposta', to='ehs.ehssessione')),
            ],
            options={
                'verbose_name': 'Notifica Data Proposta EHS',
                'verbose_name_plural': 'Notifiche Data Proposta EHS',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.CreateModel(
            name='EHSNotificaSessioneConfermataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('letta', models.BooleanField(default=False)),
                ('negozio_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehs_notifiche_conferma_store', to='stores.store')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_conferma_store', to='ehs.ehssessione')),
            ],
            options={
                'verbose_name': 'Notifica Conferma Sessione EHS (Store)',
                'verbose_name_plural': 'Notifiche Conferma Sessione EHS (Store)',
                'ordering': ['-creata_il'],
            },
        ),
    ]
