# Generated by Django 6.0.6 on 2026-09-11 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehs', '0005_ehsnotificadataproposta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ehscorso',
            name='fornitore',
            field=models.ForeignKey(blank=True, limit_choices_to={'livello_accesso': 'fornitore'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corsi_ehs_gestiti', to=settings.AUTH_USER_MODEL),
        ),
    ]
