# Generated by Django 6.0.6 on 2026-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_nove_box_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='azione',
            field=models.CharField(choices=[('crea', 'Creazione'), ('modifica', 'Modifica'), ('elimina', 'Eliminazione'), ('disattiva', 'Disattivazione'), ('riattiva', 'Riattivazione')], max_length=20),
        ),
        migrations.AlterField(
            model_name='percorsocrescita',
            name='tipo_evento',
            field=models.CharField(choices=[('promozione', 'Promozione'), ('trasferimento', 'Trasferimento'), ('cambio_ruolo', 'Cambio Ruolo'), ('nota', 'Nota')], max_length=20),
        ),
    ]
