# Generated by Django 6.0.6 on 2026-06-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_nove_box_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
