# Generated by Django 6.0.6 on 2026-06-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_richiestacreasioneprofilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestacreazioneprofilo',
            name='visto_ho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='richiestacreazioneprofilo',
            name='visto_store',
            field=models.BooleanField(default=False),
        ),
    ]
