# Generated by Django 6.0.6 on 2026-07-01 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_visto_to_richiesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaEliminazioneProfilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snap_nome', models.CharField(max_length=200)),
                ('stato', models.CharField(choices=[('pending', 'In attesa'), ('approvata', 'Approvata'), ('rifiutata', 'Rifiutata')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('visto_ho', models.BooleanField(default=False)),
                ('visto_store', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste_eliminazione_processate', to=settings.AUTH_USER_MODEL)),
                ('richiedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_eliminazione_inviate', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_eliminazione_ricevute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiesta Eliminazione Profilo',
                'ordering': ['-created_at'],
            },
        ),
    ]
