# Generated by Django 6.0.6 on 2026-07-01 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_add_area_model'),
        ('users', '0011_richiesta_eliminazione_profilo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificaTrasferimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snap_nome_utente', models.CharField(max_length=200)),
                ('snap_nome_store_origine', models.CharField(max_length=200)),
                ('letta', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_destinazione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trasferimenti_ricevuti', to='stores.store')),
                ('store_origine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trasferimenti_inviati', to='stores.store')),
                ('utente_trasferito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_trasferimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
