# Generated by Django 6.0.6 on 2026-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_add_area_model'),
        ('users', '0012_notifica_trasferimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fornitore_ragione_sociale',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='negozi_abilitati',
            field=models.ManyToManyField(blank=True, related_name='fornitori_ehs_abilitati', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='user',
            name='livello_accesso',
            field=models.CharField(choices=[('admin', 'Admin'), ('ho', 'Head Office'), ('area', 'Area Manager'), ('store', 'Store'), ('base', 'Base'), ('fornitore', 'Fornitore EHS')], default='base', max_length=10),
        ),
    ]
