# Generated by Django 6.0.6 on 2026-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_fornitore_ragione_sociale_user_negozi_abilitati_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
