# Generated by Django 6.0.6 on 2026-09-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_indirizzo_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='livello_accesso',
            field=models.CharField(choices=[('admin', 'Admin'), ('admin_ehs', 'Admin EHS'), ('ho', 'Head Office'), ('area', 'Area Manager'), ('store', 'Store'), ('base', 'Base'), ('fornitore', 'Fornitore EHS')], default='base', max_length=10),
        ),
    ]
