# Generated by Django 6.0.6 on 2026-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttivitaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipologia', models.CharField(choices=[('formazione', 'Formazione'), ('sviluppo', 'Sviluppo'), ('onboarding', 'Onboarding'), ('compliance', 'Compliance'), ('altro', 'Altro')], max_length=20)),
                ('dettaglio', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attività Catalogo',
                'verbose_name_plural': 'Attività Catalogo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('ore_totali', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('location_esterna', models.CharField(blank=True, max_length=300)),
                ('max_partecipanti', models.PositiveSmallIntegerField(default=0, help_text='0 = nessun limite')),
                ('modalita_partecipazione', models.CharField(choices=[('presenza', 'In Presenza'), ('online', 'Online'), ('blended', 'Blended')], default='presenza', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'ordering': ['data', 'ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=200)),
                ('posizione', models.CharField(choices=[('interno', 'Interno'), ('esterno', 'Esterno'), ('consulente', 'Consulente')], max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Host',
                'ordering': ['descrizione'],
            },
        ),
    ]
