# Generated by Django 6.0.6 on 2026-06-26 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attivitacatalogo',
            name='ruoli_destinatari',
            field=models.ManyToManyField(blank=True, related_name='attivita_destinate', to='users.role'),
        ),
        migrations.AddField(
            model_name='evento',
            name='attivita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='events.attivitacatalogo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_creati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='location_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_hosted', to='stores.store'),
        ),
        migrations.AddField(
            model_name='evento',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='events.host'),
        ),
    ]
