# Generated by Django 6.0.6 on 2026-07-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_notifica_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaevento',
            name='snap_creato_da',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
