# Generated by Django 6.0.6 on 2026-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_snap_creato_da'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaevento',
            name='snap_motivazione',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notificaevento',
            name='tipo',
            field=models.CharField(choices=[('nuova', 'Nuova'), ('annullata', 'Annullata')], default='nuova', max_length=20),
        ),
    ]
