# Generated by Django 6.0.6 on 2026-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_tipo_motivazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ehs_luogo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evento',
            name='is_ehs',
            field=models.BooleanField(default=False),
        ),
    ]
