# Generated by Django 6.0.6 on 2026-06-26 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='iscrizione',
            unique_together={('evento', 'user')},
        ),
    ]
