# Generated by Django 6.0.6 on 2026-07-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_richiesta_cancellazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestacancellazione',
            name='snap_tipologia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
