# Generated by Django 6.0.6 on 2026-06-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('comune', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=5)),
                ('indirizzo', models.CharField(blank=True, max_length=300)),
                ('email_store', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Store',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='StoreCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_managers', models.PositiveSmallIntegerField(default=1)),
                ('assistant_managers', models.PositiveSmallIntegerField(default=1)),
                ('department_managers', models.PositiveSmallIntegerField(default=1)),
                ('team_managers', models.PositiveSmallIntegerField(default=1)),
                ('visual_managers', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='stores.store')),
            ],
            options={
                'verbose_name': 'Cluster Store',
                'verbose_name_plural': 'Cluster Store',
            },
        ),
    ]
