# Generated by Django 6.0.6 on 2026-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='portale_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
