# Generated by Django 6.0.6 on 2026-06-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_add_codice_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('area_manager_retail', models.CharField(blank=True, max_length=200)),
                ('area_bp', models.CharField(blank=True, max_length=200)),
                ('stores', models.ManyToManyField(blank=True, related_name='aree', to='stores.store')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Aree',
                'ordering': ['numero'],
            },
        ),
    ]
